### PR TITLE
add support for Ubuntu 18

### PR DESCRIPTION
**Pull request by fujexo**
##### SUMMARY

Add Support for Ubuntu 18

##### ISSUE TYPE

 - Feature Pull Request

### CODE REVIEW

**Comment by karras** [comment]
LGTM

**Review by matsimon — CHANGES_REQUESTED** [review]
Overall, the diff is OK.

However I'd appreciate if you could update the commit message as to why we remove ufw whereas in Ubuntu_14.yml for example there is another package the is being removed.

This helps future self as to why you thought ufw needs to be absent.

I'm guessing that you want ufw to be removed because of conflicts with iptables?

**Comment by keachi** [comment]
Do we have ufw also installed on other distributions? Should we add it to every distribution?

**Review by keachi — COMMENTED** [review]
Do we have ufw also installed on other distributions? Should we add it to every distribution? If so, add it to the `debian.yml` file.

**Pull request closed without merging**
